# Ficher de déploiement de l'infrastructure du système mon-domaine
version: '3.1'

services:

  db:
    image: mysql
    container_name: c_db_mysql
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:      
      #MYSQL_ROOT_PASSWORD: Mondomaine2021
      #MYSQL_DATABASE: 
      MYSQL_USER: mon-domaine
      MYSQL_PASSWORD: Mondomaine2021
    ports:
      -3306
    volumes:
        - /Users/namorytraore1984/Documents/workshop/git-repo/mon-domaine/mon-domaine-volumes/db/mysql_home:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: c_phpmyadmin
    #restart: always
    depends_on:
        -db
    ports:
      - 8080:80
    environment:
        PMA_HOST: db
    - /Users/namorytraore1984/Documents/workshop/git-repo/mon-domaine/mon-domaine-volumes/db/phpmyadmin_home:/etc/phpmyadmin/config.user.inc.php
      
  adminer:
    image: adminer
    container_name: c_adminer
    #restart: always
    depends_on:
        -db
    ports:
      - 8080:8080